apiVersion: v1
kind: Service
metadata:
  name: simple-python-api-argocd
  namespace: simple-python-api-argocd
spec:
  type: NodePort
  selector:
    app: simple-python-api-argocd
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
